#ifndef CONTSTANTS_H
#define CONTSTANTS_H

#include <QStringList>
#include <QVector>
#include <QIntValidator>
#include "Property.h"

const QStringList NamesOfProp({"TLP_ENABLE", "TLP_DEFAULT_MODE", "DISK_IDLE_SECS_ON_AC", "DISK_IDLE_SECS_ON_BAT",
                               "MAX_LOST_WORK_SECS_ON_AC", "MAX_LOST_WORK_SECS_ON_BAT", "CPU_SCALING_GOVERNOR_ON_AC",
                               "CPU_SCALING_GOVERNOR_ON_BAT", "CPU_SCALING_MIN_FREQ_ON_AC", "CPU_SCALING_MAX_FREQ_ON_AC",
                               "CPU_SCALING_MIN_FREQ_ON_BAT", "CPU_SCALING_MAX_FREQ_ON_BAT", "CPU_MIN_PERF_ON_AC",
                               "CPU_MAX_PERF_ON_AC", "CPU_MIN_PERF_ON_BAT", "CPU_MAX_PERF_ON_BAT", "CPU_BOOST_ON_AC",
                               "CPU_BOOST_ON_BAT", "SCHED_POWERSAVE_ON_AC", "SCHED_POWERSAVE_ON_BAT", "NMI_WATCHDOG",
                               "PHC_CONTROLS", "ENERGY_PERF_POLICY_ON_AC", "ENERGY_PERF_POLICY_ON_BAT", "DISK_DEVICES",
                               "DISK_APM_LEVEL_ON_AC", "DISK_APM_LEVEL_ON_BAT", "DISK_SPINDOWN_TIMEOUT_ON_AC",
                               "DISK_SPINDOWN_TIMEOUT_ON_BAT", "DISK_IOSCHED", "SATA_LINKPWR_ON_AC", "SATA_LINKPWR_ON_BAT",
                               "PCIE_ASPM_ON_AC", "PCIE_ASPM_ON_BAT", "RADEON_POWER_PROFILE_ON_AC", "RADEON_POWER_PROFILE_ON_BAT",
                               "RADEON_DPM_STATE_ON_AC", "RADEON_DPM_STATE_ON_BAT", "RADEON_DPM_PERF_LEVEL_ON_AC",
                               "RADEON_DPM_PERF_LEVEL_ON_BAT", "WIFI_PWR_ON_AC", "WIFI_PWR_ON_BAT", "WOL_DISABLE",
                               "SOUND_POWER_SAVE_ON_AC", "SOUND_POWER_SAVE_ON_BAT", "SOUND_POWER_SAVE_CONTROLLER",
                               "BAY_POWEROFF_ON_BAT", "BAY_DEVICE", "RUNTIME_PM_ON_AC", "RUNTIME_PM_ON_BAT", "RUNTIME_PM_ALL",
                               "RUNTIME_PM_BLACKLIST", "RUNTIME_PM_DRIVER_BLACKLIST", "USB_AUTOSUSPEND", "USB_BLACKLIST",
                               "USB_BLACKLIST_WWAN", "USB_WHITELIST", "USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN",
                               "RESTORE_DEVICE_STATE_ON_STARTUP", "DEVICES_TO_DISABLE_ON_STARTUP", "DEVICES_TO_ENABLE_ON_STARTUP",
                               "DEVICES_TO_DISABLE_ON_SHUTDOWN", "DEVICES_TO_ENABLE_ON_SHUTDOWN", "DEVICES_TO_ENABLE_ON_AC",
                               "DEVICES_TO_DISABLE_ON_BAT", "DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE", "START_CHARGE_THRESH_BAT0",
                               "STOP_CHARGE_THRESH_BAT0", "START_CHARGE_THRESH_BAT1", "STOP_CHARGE_THRESH_BAT1",
                               "DEVICES_TO_DISABLE_ON_LAN_CONNECT", "DEVICES_TO_DISABLE_ON_WIFI_CONNECT",
                               "DEVICES_TO_DISABLE_ON_WWAN_CONNECT", "DEVICES_TO_ENABLE_ON_LAN_DISCONNECT",
                               "DEVICES_TO_ENABLE_ON_WIFI_DISCONNECT", "DEVICES_TO_ENABLE_ON_WWAN_DISCONNECT",
                               "DEVICES_TO_ENABLE_ON_DOCK", "DEVICES_TO_DISABLE_ON_DOCK", "DEVICES_TO_ENABLE_ON_UNDOCK",
                               "DEVICES_TO_DISABLE_ON_UNDOCK"});

//enum TypeOfWidget{QLineEdit, QCheckBox, QComboBox};
//enum PropertyGroup{MAIN, CPU, DISK, THINKPAD, RADIO, RADEON, USB, PCI, OTHER};




const int NumOfProp = NamesOfProp.size(), NumOfColumn = 3;
enum TypeColumn {COL_ACTIVE, COL_NAME, COL_VALUE};

#endif // CONTSTANTS_H
